name: Verify Action

on:
  deployment:
  pull_request:
    branches: [develop]

jobs:
  verify:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Wait for Environment
        uses: ./
        with:
          environment: 'staging.alpha.bluescape.io'
          timeout: 1
